FROM alpine:latest AS base

# Env Vars we need set at image runtime in order to control grate
ENV GRATE_ENVIRONMENT="Dev"
ENV GRATE_CONNSTRING=""

WORKDIR /app

# Build arguments we configure at image build time.
# Use the uniqur build number as the database version in this case
ARG BUILD_BUILDNUMBER
ENV VERSION=$BUILD_BUILDNUMBER

# Get the sql scripts into the image
COPY ./db ./db

# grate is self-contained, but you may consider specifying a version number for consitency
RUN dotnet tool install dotnet-grate -g 

# TODO: Where do self-contained .net 6 apps go?
ENTRYPOINT dotnet /root/.dotnet/tools/.store/dotnet-grate/1.3.1/dotnet-roundhouse/1.3.1/tools/netcoreapp3.1/any/rh.dll \
/f=db /v=$VERSION /env=$GRATE_ENVIRONMENT /cs=$GRATE_CONNSTRING -simple -tx -silent 
