# TODO: Swap to alpine:latest once grate is published
FROM mcr.microsoft.com/dotnet/sdk:3.1-alpine AS base

# Env Vars we need set at image runtime in order to control grate
ENV GRATE_CONNSTRING=""

WORKDIR /app

# Get the sql scripts into the image
COPY ./db ./db

# grate is self-contained, but you may consider specifying a version number for consitency
# RUN dotnet tool install dotnet-grate -g 
RUN dotnet tool install -g dotnet-roundhouse

# TODO: Where do self-contained .net 6 apps go?
ENTRYPOINT sleep 30 &  dotnet /root/.dotnet/tools/.store/dotnet-roundhouse/1.3.1/dotnet-roundhouse/1.3.1/tools/netcoreapp3.1/any/rh.dll \
-f=db -v=1.0.0.0 -cs="$GRATE_CONNSTRING" -db=grate_test -silent --verbose --dt=postgres
