FROM erikbra/grate:latest

# Env Vars we need set at image runtime in order to control grate
ENV APP_CONNSTRING=""

# We set the app-version at build time, as it's the same regardless of environment
ARG APP_VERSION
ENV VERSION=$APP_VERSION

WORKDIR /app

# Get the sql scripts into the image
COPY ./db ./db
RUN mkdir /app/migration-output

ENTRYPOINT ./grate \
-f=db --version=$VERSION --connstring="$APP_CONNSTRING" -silent --outputPath=./migration-output
