# Created using wingetcreate 0.4.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: erikbra.grate
PackageVersion: 0.10.1
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  InstallerUrl: https://github.com/erikbra/grate/releases/download/0.10.1/grate-0.10.1.msi
  InstallerSha256: A17831A175607DAFD47F55B4B82D144889415CA1CF34B4EFF0BA58E2A3EC3398
  ProductCode: '{E281998A-D8A2-4926-AAA3-066EFA4B2E74}'
ManifestType: installer
ManifestVersion: 1.0.0

