using SqlServerCaseSensitive.TestInfrastructure;
using TestCommon.Generic.Running_MigrationScripts;
using TestCommon.TestInfrastructure;

namespace SqlServerCaseSensitive.Running_MigrationScripts;
public abstract class SqlServerScriptsBase : MigrationsScriptsBase;
