#!/bin/sh
set -e
# Automatically added by dh_installdocs
if [ "$1" = "configure" ]; then
  if [ -d /usr/doc -a ! -e /usr/doc/grate -a -d /usr/share/doc/grate ]; then
    ln -sf ../share/doc/grate /usr/doc/grate
  fi
fi