FROM erikbra/grate:latest as base
WORKDIR /app
COPY sql/ /db
RUN mkdir /output
ENTRYPOINT ./grate \
            --sqlfilesdirectory=/db \
            --version=$VERSION \
            --connstring="$APP_CONNSTRING" \
            --silent \
            --databasetype=sqlserver \
            --outputPath=/output